print("Nombre, Alexis Davd Zambrano Ibarra")
print("Lugra de residencia, Rincon de Romos")
print ("Fecha de nacimiento, 01/02/2002")
print("Color Favorito, Morado y azul")
print("Animal Favorito, Gato y Tiburon")

print ("¿Que es la programacion")
print("Es la manera en que se crea una vista de la realidad basada en distinto objetos")
print("¿Por que es importante la programacion?")
print("Para la realizacion de mejoras y mantenimientos de programas y creacion de nuevos, esto con el fin de mejorar los sistemas y autmatizar acciones")
print("HERENCIA: ")
print("Una clase puede heredar atributos a objetos, no es necesario que tenga todos los rasgos de esa clase, un ejemplo son los electrodomésticos, todos tienen un conjunto de características similares como lo son los cables, interruptores, etc.")
print("POLIFORMISMO:")
print("Le dan distintas acciones a palabras o comandos dependiendo de los objetos a los que este orientada, como la palabra abrir tiene distintas funciones de una puerta a la de una caja")
print("ABSTRACCION:")
print("En el software esto se refiere a poner menos datos para realizar acciones que no requieren de todas los rasgos de un grupo y solo tome los necesarios, esto reduce el tiempo de trabajo y el uso de recursos")
print("ENCAPSULAMIENTO")
print("Permite el dar una imagen o funcionamiento al mundo exterior sin necesidad de mostrar todos los procesos que estos conllevan, tambien se le conoce como ocultamiento de la información")